baseURL = 'https://www.plakar.io/'
languageCode = 'en-us'
theme = "plakarium"
title = "Plakar | The Open Standard for Backup and Restore"


ignoreFiles = ["content/templates/.*"]

[Params]
latest = 'v1.0.6'
description =  "Enterprise ready backups with developer friendly tooling. Encrypted, deduplicated snapshots, instant browsing and restore, and zero knowledge workflows across clouds and on-prem."
author = "Nestor"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [['$$', '$$']]
  inline = [['\\(', '\\)']]

[highlight]
  noClasses = false


[permalinks]
posts = "/posts/:year-:month-:day/:slug"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"

[Params.github]
enabled = true
organization = "PlakarKorp"
repository = "plakar"

[Params.discord]
enabled = true
inviteCode = "uuegtnF2Q5"
serverID = "1281181647005421589"

[Params.reddit]
enabled = true
communityName = "plakar"

[Params.bluesky]
enabled = true
account = "plakar.bsky.social"

[Params.X]
enabled = true
account = "PlakarKorp"

[Params.linkedin]
enabled = true
companyID = "plakarkorp"

[Params.axeptio]
enabled = true
clientId = "670b04f487d8b40de2e7f22c"
cookiesVersion = "plakar-fr-EU-2"

[Params.googleAnalytics]
enabled = true
id = "G-4EJ3HLL4HS"
