# ----------- Top-level items -----------

[[main]]
identifier = "solutions"
name = "Solution"
url = "#"
weight = 10
[[main.params]]
    enabled = true

[[main]]
identifier = "engineering"
name = "Engineering"
url = "#"
weight = 20
[[main.params]]
    enabled = true

[[main]]
identifier = "integrations"
name = "Integrations"
url = "/integrations/"
weight = 30
[[main.params]]
    enabled = true

[[main]]
identifier = "download"
name = "Download"
url = "/download/"
weight = 40
[[main.params]]
    enabled = true

[[main]]
identifier = "pricing"
name = "Pricing"
url = "/pricing/"
weight = 50
[[main.params]]
    enabled = false



# ----------- Solutions > Platforms -----------

[[main]]
identifier = "solutions-onpremises-backup"
name = "On-premises"
url = "/solutions/backup-and-restore/"
weight = 10
parent = "solutions"
[[main.params]]
    description = "On your infrastructure"
    enabled = true
    section = "Platforms"
    section_weight = 10
    icon = "ri:refresh-line"

[[main]]
identifier = "solutions-cloud-aws"
name = "AWS"
url = "#"
weight = 20
parent = "solutions"
[[main.params]]
    enabled = true
    section = "Platforms"
    section_weight = 10
    icon = "AWS"

[[main]]
identifier = "solutions-cloud-gcp"
name = "Google Cloud"
url = "#"
weight = 30
parent = "solutions"
[[main.params]]
    enabled = true
    section = "Platforms"
    section_weight = 10
    icon = "Google-Cloud"

[[main]]
identifier = "solutions-cloud-azure"
name = "Azure"
url = "#"
weight = 40
parent = "solutions"
[[main.params]]
    enabled = true
    section = "Platforms"
    section_weight = 10
    icon = "Microsoft-Azure"


[[main]]
identifier = "solutions-cloud-ovh"
name = "OVH"
url = "#"
weight = 50
parent = "solutions"
[[main.params]]
    enabled = true
    section = "Platforms"
    section_weight = 10
    icon = "OVH"

# ----------- Solutions > Services -----------

[[main]]
identifier = "solutions-services-kubernetes"
name = "Kubernetes"
url = "/solutions/plakar-for-kubernetes/"
weight = 10
parent = "solutions"
[[main.params]]
    description = "Backup your clusters"
    enabled = true
    section = "Services"
    section_weight = 20
    icon = "Kubernetes"

[[main]]
identifier = "solutions-services-proxmox"
name = "Proxmox"
url = "/solutions/plakar-for-kubernetes/"
weight = 20
parent = "solutions"
[[main.params]]
    description = "Backup your VMs"
    enabled = true
    section = "Services"
    section_weight = 20
    icon = "Proxmox"

[[main]]
identifier = "solutions-services-notion"
name = "Notion"
url = "/solutions/plakar-for-notion/"
weight = 30
parent = "solutions"
[[main.params]]
    description = "Backup your workspace"
    enabled = true
    section = "Services"
    section_weight = 20
    icon = "Notion"

# ----------- Solutions > Resources -----------

[[main]]
identifier = "solutions-resources-compare"
name = "Compare Plakar to Alternatives"
url = "#"
weight = 40
parent = "solutions"
[[main.params]]
    description = "Discover Plakar strengths"
    enabled = true
    section = "Resources"
    section_weight = 30
    icon = "ri:arrow-left-right-line"

[[main]]
identifier = "solutions-resources-reduce-costs"
name = "Reduce Backup Costs"
url = "#"
weight = 40
parent = "solutions"
[[main.params]]
    description = "Better coverage less costs"
    enabled = true
    section = "Resources"
    section_weight = 30
    icon = "ri:arrow-left-right-line"

[[main]]
identifier = "solutions-resources-review"
name = "Product review"
url = "#"
weight = 50
parent = "solutions"
[[main.params]]
    description = "Engineers feedback"
    enabled = false
    section = "Resources"
    section_weight = 20
    icon = "ri:chat-quote-line"

# ----------- Engineering > Learn -----------

[[main]]
identifier = "engineering-learn-quickstart"
name = "Quick start"
url = "/docs/LATEST_VERSION_PLACEHOLDER/quickstart/"
weight = 10
parent = "engineering"
[[main.params]]
    description = "Protect your data in a minute"
    enabled = true
    section = "Learn"
    section_weight = 10
    icon = "ri:rocket-2-line"
    target = "_blank"

[[main]]
identifier = "engineering-learn-docs"
name = "Documentation"
url = "/docs/LATEST_VERSION_PLACEHOLDER/"
weight = 20
parent = "engineering"
[[main.params]]
    description = "How to use Plakar?"
    enabled = true
    section = "Learn"
    section_weight = 10
    icon = "ri:book-open-line"
    target = "_blank"

[[main]]
identifier = "engineering-learn-blog"
name = "Plakar blog"
url = "/posts/"
weight = 30
parent = "engineering"
[[main.params]]
    description = "Engineers thought & last news"
    enabled = true
    section = "Learn"
    section_weight = 10
    icon = "ri:article-line"

# ----------- Engineering > Community -----------

[[main]]
identifier = "engineering-community-join"
name = "Plakar community"
url = "community/"
weight = 40
parent = "engineering"
[[main.params]]
    description = "Open by default, join us!"
    enabled = true
    section = "Community"
    section_weight = 20
    icon = "ri:team-line"

[[main]]
identifier = "engineering-community-calendar"
name = "Upcoming events"
url = "contact/#upcoming-events"
weight = 40
parent = "engineering"
[[main.params]]
    description = "Meet Plakar team"
    enabled = true
    section = "Community"
    section_weight = 20
    icon = "ri:calendar-event-line"

[[main]]
identifier = "contact-us"
name = "Contact us"
url = "/contact/#email-contact"
weight = 50
parent = "engineering"
[[main.params]]
    description = "How to contact Plakar team?"
    enabled = true
    section = "Community"
    section_weight = 20
    icon = "ri:mail-line"

[[main]]
identifier = "engineering-community-events"
name = "Incoming events"
url = "#"
weight = 50
parent = "engineering"
[[main.params]]
    description = "Live events with Plakar team"
    enabled = false
    section = "Community"
    section_weight = 20
    icon = "ri:calendar-2-line"

[[main]]
identifier = "engineering-community-newsletter"
name = "Newsletter"
url = "contact/#newsletter-signup"
weight = 60
parent = "engineering"
[[main.params]]
    description = "Receive our monthly newsletter"
    enabled = true
    section = "Community"
    section_weight = 20
    icon = "ri:mail-ai-line"

[[main_docs]]
identifier = "documentation"
name = "Documentation"
url = "/docs/"
weight = 10
[[main_docs.params]]
enabled = true

[[main_docs]]
identifier = "quickStart"
name = "Quick start"
url = "/docs/LATEST_VERSION_PLACEHOLDER/quickstart/"
weight = 20
[[main_docs.params]]
enabled = true
